name: fast-ngs-admix
channels:
  - defaults
  - conda-forge
  - bioconda
  - r
  - anaconda
dependencies:
  - r-base=3.6.0
  - r-maps=3.3.0
  - conda-forge::r-r.methodss3=1.7.1
  - conda-forge:r-flexdashboard=0.5.1.1
  - conda-forge::r-ggpubr=0.2.3
  - conda-forge::r-readr=1.3.1
  - fonts-anaconda=1
  - conda-forge::r-rmarkdown=1.18
  - r-tidyverse=1.2.1
  - bioconductor-affy=1.62.0
  - bioconductor-affyio=1.54.0
  - bioconda::bioconductor-biobase=2.44.0
  - bioconda::bioconductor-biocgenerics=0.30.0
  - bioconda::bioconductor-cll=1.24.0 
  - bioconductor-limma=3.40.2
  - bioconda::bioconductor-preprocesscore=1.46.0
  - bioconductor-zlibbioc=1.30.0
  - r-assertthat=0.2.1
  - r-backports=1.1.4
  - conda-forge::r-biocmanager=1.30.4
  - r-callr=3.3.1
  - r-cli=1.1.0
  - r-clipr=0.7.0
  - r-colorspace=1.4-1
  - r-crayon=1.3.4
  - r-data.table=1.12.2
  - r-desc=1.2.0
  - r-devtools=2.1.0
  - r-digest=0.6.20
  - r-dplyr=0.8.3
  - conda-forge::r-dt=0.8
  - r-evaluate=0.14
  - r-fs=1.3.1
  - r-ggfittext=0.8.1
  - r-ggplot2=3.2.1
  - r-ggrepel=0.8.1
  - r-glue=1.3.1
  - r-gtable=0.3.0
  - r-here=0.1
  - r-hms=0.5.0
  - r-htmltools=0.3.6
  - r-htmlwidgets=1.3
  - r-httr=1.4.1
  - r-jsonlite=1.6
  - r-knitr=1.24
  - r-lazyeval=0.2.2
  - r-magrittr=1.5
  - r-memoise=1.1.0
  - r-munsell=0.5.0
  - r-pillar=1.4.2
  - r-pkgbuild=1.0.4
  - r-pkgconfig=2.0.2
  - r-pkgload=1.0.2
  - conda-forge::r-plotly=4.9.0
  - r-prettyunits=1.0.2
  - r-processx=3.4.1
  - r-progress=1.2.2
  - r-ps=1.3.0
  - r-purrr=0.3.2
  - conda-forge::r-r6=2.4.0 
  - conda-forge::r-rcolorbrewer=1.1_2
  - conda-forge::r-rcpp=1.0.2
  - r-readr=1.3.1
  - r-remotes=2.1.0
  - r-rlang=0.4.0
  - r-rprojroot=1.3-2
  - r-rstudioapi=0.10
  - r-scales=1.0.0
  - r-sessioninfo=1.1.1
  - conda-forge::r-skimr=1.0.7
  - r-testthat=2.2.1
  - r-tibble=2.1.3
  - r-tidyr=0.8.3
  - r-tidyselect=0.2.5
  - r-usethis=1.5.1
  - r-vctrs=0.2.0
  - r-withr=2.1.2
  - r-xml2=1.2.2
  - r-yaml=2.2.0
  - fonts-anaconda=1
