name: base
channels:
  - conda-forge
  - defaults
dependencies:
  - conda
  - python=3.7
  - pip
  - tini=0.18.0
  - jupyterhub=1.1.0
  - notebook=6.0.3
  - jupyterlab=1.2.5
  - matplotlib-base=3.1
  - cloudpickle=1.2
  - numba=0.48
  - conda-forge::blas[build=openblas]
  - sqlalchemy=1.3
  - cython=0.29
  - vincent=0.4
  - dask=2.9
  - seaborn=0.9
  - statsmodels=0.11
  - xlrd
  - scipy=1.4
  - scikit-learn=0.22
  - hdf5=1.10
  - sympy=1.5
  - pandas=0.25
  - beautifulsoup4=4.8
  - bokeh=1.4
  - ipywidgets=7.5
  - patsy=0.5
  - dill=0.3
  - h5py=2.10
  - protobuf=3.11
  - numexpr=2.7
  - scikit-image=0.16
  - r-htmlwidgets=1.5
  - r-shiny=1.3
  - r-forecast=8.10
  - r-htmltools=0.4
  - r-devtools=2.2
  - r-caret=6.0
  - r-randomforest=4.6
  - r-nycflights13=1.0
  - r-base=3.6.2
  - r-tidyverse=1.3
  - r-rsqlite=2.1
  - rpy2=3.1
  - r-irkernel=1.1
  - r-plyr=1.8
  - r-hexbin=1.28
  - r-rmarkdown=2.1
  - r-rcurl=1.98
  - r-reshape2=1.4
  - r-crayon=1.3
  - jupytext
  - conda-forge::r-europepmc

